apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vault-root-ca
  namespace: cert-manager
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  isCA: true
  commonName: vault-root-ca
  secretName: vault-root-ca-secret
  privateKey:
    algorithm: RSA
    size: 4096
  issuerRef:
    name: vault-root-selfsigned
    kind: ClusterIssuer