apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cm-smoke-cert
  namespace: default
spec:
  secretName: cm-smoke-cert-tls
  issuerRef:
    name: cm-smoke-cluster-selfsigned
    kind: ClusterIssuer
  commonName: smoke.default.svc.cluster.local