apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./mtls/cluster-issuer-ca.yaml
  - ./mtls/vault-server-cert.yaml
  - ./mtls/openbao-server-cert.yaml
  - ./trust-manager/trust-bundle.yaml
  - ./client-certificate
