apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patchesStrategicMerge:
  - namespace-patch.yaml

helmCharts:
  - name: vault
    repo: https://helm.releases.hashicorp.com
    version: "0.32.0"
    releaseName: vault-dev
    namespace: vault-dev
