apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra-service
  namespace: argocd
  # annotations:
  #   argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    repoURL: https://github.com/Mariozdz/Gitops_Vault.git
    targetRevision: main
    path: infra/
  destination:
    server: https://kubernetes.default.svc
    namespace: infra-service-ns
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true