global:
  tlsDisable: false

server:
  extraLabels:
    app.kubernetes.io/name-test: openbao-server
    app.kubernetes.io/component: server
    security-tier: critical

  service:
    labels:
      app.kubernetes.io/name-svc-test: openbao-svc-test
      security-tier: critical

  image:
    registry: quay.io
    repository: openbao/openbao
    tag: "2.5.1"

  standalone:
    enabled: false

  securityContext:
    runAsNonRoot: true
    runAsUser: 100
    runAsGroup: 1000
    fsGroup: 1000

  volumes:
    - name: openbao-tls
      secret:
        secretName: openbao-tls
        defaultMode: 0400
    - name: cluster-trust
      configMap:
        name: cluster-trust

  volumeMounts:
    - name: openbao-tls
      mountPath: /openbao/ssl
      readOnly: true
    - name: cluster-trust
      mountPath: /etc/ssl/certs/cluster-ca.pem
      subPath: ca.crt
      readOnly: true

  ha:
    enabled: true
    replicas: 1
    raft:
      enabled: true
      setNodeId: true

      config: |
        ui = true

        listener "tcp" {
          address     = "0.0.0.0:8200"
          cluster_address = "0.0.0.0:8201"

          tls_cert_file = "/openbao/ssl/tls.crt"
          tls_key_file = "/openbao/ssl/tls.key"
          
          tls_client_ca_file = "/openbao/ssl/ca.crt"
          tls_disable_client_certs = "false"
        }

        storage "raft" {
          path = "/openbao/data"
        }

        api_addr = "https://openbao.openbao.svc:8200"
        service_registration "kubernetes" {}

  dataStorage:
    enabled: true
    size: 1Gi

injector:
  enabled: true
  extraLabels:
    app.kubernetes.io/name-test: bao-agent-injector-test
    security-tier: critical

ui:
  enabled: true