apiVersion: trust.cert-manager.io/v1alpha1
kind: Bundle
metadata:
  name: cluster-trust
spec:

  sources:
    #- useDefaultCAs: true
    - secret:
        name: root-ca
        key: ca.crt

  target:

    configMap:
      key: ca.crt

    namespaceSelector: {}