global:
  tlsDisable: false

server:
  image:
    repository: hashicorp/vault
    tag: "1.21.2"

  replicas: 1

  standalone:
    enabled: false

  extraVolumes:
    - name: vault-tls
      secret:
        secretName: vault-tls
        defaultMode: 0400

  extraVolumeMounts:
    - name: vault-tls
      mountPath: /vault/ssl
      readOnly: true

  ha:
    enabled: true
    replicas: 1
    raft:
      enabled: true
      setNodeId: true

      config: |
        ui = true

        listener "tcp" {
          address     = "0.0.0.0:8200"
          cluster_address = "0.0.0.0:8201"

          tls_cert_file = "/vault/ssl/tls.crt"
          tls_key_file = "/vault/ssl/tls.key"
        }

        storage "raft" {
          path = "/vault/data"
        }

        api_addr = "https://vault.vault.svc:8200"
        service_registration "kubernetes" {}


  dataStorage:
    enabled: true
    size: 1Gi

ui:
  enabled: true